name: this is workflows test

on:
  # Manual update only.
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: xxx
        run:
          GIT_DEPLOY_REPO="https://${{ github.token }}@github.com/${{ github.repository }}.git"
          echo $GIT_DEPLOY_REPO
